### ISSUE TITLE
Request to Join Project Communications: albendz

### ISSUE THREAD

**Issue by albendz** [pyladies/project-communications#12]
_This template should be used (edited) for PyLadies members that wish to join the Project Communications team.

**Proposed Team Member Details**

Name           | GitHub Handle | PyLadies Chapter               | Team Role    | Pyladies Slack
-- | -- | -- | -- | --
Alicia Bendz |  @albendz        | None (I'm in Philadelphia) | Contributor | abendz

**Why do you want to join the PyLadies Project Communications team?**

I'm interested in contributing to and helping maintain the Pyladies blog and Slack channels. I want to help build a remote community because I want to build more remote culture in the industry and I want to help PyLadies to be available to everyone even if they aren't in a city with a chapter (like me).

I'm already in the project-communication channel on Pyladies Slack.

/cc @pyladies/communications

**Comment by Caaddss** [comment]
@albendz Hi girl!!!  How are you?!! Its amazing your idea and interesting to colaborator with us!! Thank you for that!! We going to go discuss about the project Monday!! Do you see on the channel?

**Comment by albendz** [comment]
Got it and I've filled out the survey - thank you!

**Comment by lorenanicole** [comment]
@albendz you've been invited to https://github.com/orgs/pyladies/teams/communications! Thanks for reaching out and you're ✅ !
