### ISSUE TITLE
Criteria and Workflow for New Members and Approvals

### ISSUE THREAD

**Issue by albendz** [pyladies/project-communications#13]
Project communications would like new members to apply to join our group through a GitHub issue. We need to define criteria for a new member joining. For example:
* Reasonable command of written and spoken English
* Membership in PyLadies
* Specific project of interest by adding a link to an issue they're interested in within this project
* etc.

Once a Github issue has been opened, we need an approval process. This includes:
* Who is responsible for responding to issues
* Goal for how quickly we get back to an issue (first response vs. resolution)
* Discussion process to determine whether we need a new contributor (slack or github?)
* Approval process that may include specific project or issue leads
* Actions taken when approval is accepted or declined - this might mean there are too many people contributing in one area and we ask if this person is interested in another way of contributing

This issue is resolved when:
* We have a new new member template requesting relevant information for determining if criteria is met
* A description of membership criteria in the new member template and in the CONTRIBUTING.md document
* An agreed upon process from the project communications team
* Identified members who will be watching for new member issues

Additional info:
@Marie-L is working on an About Me template to be added to the join request. This can be added later or in the first issue template.

We can consider a period of inactivity where afterwards members are removed from the contributors list.

**Comment by Marie-L** [comment]
Some really great points here, thanks for raising this issue @albendz !

**Comment by Marie-L** [comment]
Hey @albendz ,Abigail and I have already started discussing best practices and work flow for the team. We would like to share with you our work so far, so please us know when you are available to discuss this in more detail.

**Comment by voru588** [comment]
Hello everyone,
Also, do we want to see their LinkedIn before making the decision?
Just an idea)

**Comment by Marie-L** [comment]
Hey @voru588, what kind of information would you like to see on their profiles? I think we should try to not to screen people in a way that an employer would. We want to encourage people to take part and we want them to feel at ease 😊. What do you think ?

**Comment by AbigailMesrenyameDogbe** [comment]
Seeing their linkedin profile is not a bad idea. But i think we could ask questions like "could you kindly share a link to your profile or a project you have worked on in this field you have chosen?"

**Comment by voru588** [comment]
@Marie-L @AbigailMesrenyameDogbe Both of you have excellent points. Maybe adding an option to state a number of years of experience with Python (for stats, for example), so even if the person has less than a year of experience, but wants to contribute, she will not be discouraged from applying.

So far, being a PyLadies member and the English language are the main criteria for the application?

Also, maybe writing a small proposal on how this person can contribute?

**Comment by Marie-L** [comment]
@voru588 Thank you for your suggestions ! My apologies as I've just seen this now. Myself, @AbigailMesrenyameDogbe & @albendz had a meeting about this yesterday. Please find the notes [here](https://docs.google.com/document/d/1KyyJCymQ27-8qQXkW2SDVs2HbhxEUkA_fugTa2c6SwQ/edit?usp=sharing). I think it would be good to have another meeting after the holiday period to continue discussing this further. It would be great to hear more about your ideas. Would you like join us next time around ?
