### ISSUE TITLE
Create a communications team calendar

### ISSUE THREAD

**Issue by Marie-L** [pyladies/project-communications#14]
Set up a a cross chapter calendar so that our team knows what workshops/talks are being planned etc. This will support ticket #2

**Comment by Marie-L** [comment]
Hey @Caaddss we spoke about this briefly before, are you still interested in helping out ?

**Comment by Caaddss** [comment]
@Marie-L Yes!!! Lets do it happens :)

**Comment by Marie-L** [comment]
@Caaddss Ok great! I'll assign you and let's discuss how to go about this. I think google or mac calendar would be a good but you mentioned creating a python calendar. Could you please explain this in more detail ?

**Comment by Caaddss** [comment]
We can use the Google API to make a Calendar

Python has a module calendar, but I dont know if support add events...

The other possibility is using generate calendar with markdown...we could create a template to add events

**Comment by Marie-L** [comment]
@Caaddss these are nice ideas but let's try to use a tool that will be quick to set up, easy for everyone to use and also can integrate well with other applications. I came across this article about the [google calendar](https://wiredimpact.com/blog/8-reasons-to-use-google-calendar/), when you have time please let me know what you think

**Comment by Caaddss** [comment]
@Marie-L sure!!

we can use google calendar, for me its ok

**Comment by Caaddss** [comment]
the good point to google calendar is: we can integrate with slack

**Comment by Marie-L** [comment]
the link for our new calendar is [here](https://calendar.google.com/calendar/embed?src=pyfound.org_3boidhk6jdjo6df9hootc64r90%40group.calendar.google.com&ctz=America%2FChicago)

**Comment by Marie-L** [comment]
**Instructions:**
Add calendar events by issuing a Slack command. for example typing out `@pyladies-bot create event: Vancouver meetup  Feb 28 5 pm GMT` will add an event to the **PyLadies Event calendar**.

**Comment by Marie-L** [comment]
The calendar has now been set up so this issue will be closed
