### ISSUE TITLE
create team wiki

### ISSUE THREAD

**Issue by Marie-L** [pyladies/project-communications#15]
my initial idea was to create a wiki for our team, but after more thought it didn't seem necessary because we could just save 'wiki' type files in our main repo like the other teams do

**Comment by Marie-L** [comment]
I've now created the first _wiki_ dir [here](https://github.com/pyladies/project-communications/tree/master/user-manual-for-me) and I plan to create directories for each area or theme. Please let me know what you think @AbigailMesrenyameDogbe

**Comment by AbigailMesrenyameDogbe** [comment]
Great

**Comment by Marie-L** [comment]
The idea to create directories within the repo for each area or theme has been agreed and implementation has begun so I will close this ticket.
