### ISSUE TITLE
Encouraging all chapters to support & engage remote learners

### ISSUE THREAD

**Issue by Marie-L** [pyladies/project-communications#2]
# Overview

The Pyladies remote chapter aims to provide learning materials for learners all around the world, however I would like to investigate whether this model could be integrated into every pyladies chapter. 

## Things to think about

- how can pyladies remote webcasts be accessed more easily (i.e slack, pyladies blog etc)?
- what are the practicalities of each chapter documenting their workshops either as webcast, slides etc?
- what kind of content is missing from the pyladies resource list that can be generated by other chapters ?
- should there be a few chapters that pilot this proposed method ?
- how can the content be shared and promoted so that it accesses people who aren't able to attend meetups etc?

**Comment by eyspahn** [comment]
One thought I had: on the revamped blog, we could have a weekly feature where we post a past conference talk by a PyLady. We could ask chapters to suggest videos their members participated in or attended.

**Comment by Marie-L** [comment]
@eyspahn Yes, that's a great idea ! Maybe we could put out a slack poll on each chapter's channel to find out for example which past conferences people would like to be featured etc. What do you think ?

**Comment by albendz** [comment]
We can consider a Pyladies Twitch channel for remote presentations and chat from the community. I've seen several developers do coding streams on the platform.

**Comment by Marie-L** [comment]
Nice idea @albendz ! Could we discuss this more at the next meeting ?
