### ISSUE TITLE
Investigate Social Media for PyLadies Communications

### ISSUE THREAD

**Issue by albendz** [pyladies/project-communications#20]
Let's look into what social media we'd like to be involved in, if any. Instagram and Twitter are commonly used by other organizations like Women Who Code. A separate issue is open to investigate voice and video streaming #19 

This issue can be resolved when:
* We've identified what platforms we want a presence on
* Types of content we want to produce

Follow up issues can be created as needed for things such as:
* Content writing and review
* Frequency of updates
* Who manages the account and content

Some of the follow up issues may already be resolved when we start working on blog and newsletter updates in #1

**Comment by voru588** [comment]
I can do a bit of research before our next meeting next week.

**Comment by albendz** [comment]
@voru588 Any updates? I want to make sure I don't repeat your work for this issue

**Comment by voru588** [comment]
@albendz , Sorry, could not get to it. I think I went over my head
Anyway, thank you for checking with me.

**Comment by albendz** [comment]
Sure - do you think you'll have time later or should I unassign? @voru588
