### ISSUE TITLE
PyLadies Chapter Social Media Guidelines

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/project-communications#25]
# Overview

PyLadies doesn't have a set of guidelines to offer chapters for how they use social media, it would be great to provide this to help community organizers know how to build their chapter while also being on brand.

## Scope of Work

Some questions to think about for what guidelines would look like:
- What is the appropriate use of social media?
- How do we use social media to build a chapter's community?
- What guidelines do we need to ensure our content upholds the PyLadies Code of Conduct?

## Deliverables

- [ ] Guidelines approved by Project Comms 
     - [ ] Writing the guidelines
     - [ ] Present to Global Interim Team (CC: @pyladies/pyladies-global-contributors @pyladies/pyladies-global-admin )
- [ ] Add guidelines into github.com/pyladies/pyladies `pip install pyladies` toolkit
    - [ ] Open PR for @pyladies/admin-and-logistics to review and ✅

**Comment by albendz** [comment]
I'd like to help with this but I haven't done anything similar before. I can take a stab at creating a draft. How does that sound?

**Comment by lorenanicole** [comment]
@albendz thats awesome! This is meant to be a collaborative doc. Some places to maybe look to start ... check out R Ladies! See: https://github.com/rladies/starter-kit/blob/master/Social_Media_Guide_for_Chapters.pdf.

**Comment by Marie-L** [comment]
thanks for the link @lorenanicole ! I'll try to put together a draft this week
