### ISSUE TITLE
Election Comms Strategy : advert artwork & copy

### ISSUE THREAD

**Issue by Marie-L** [pyladies/project-communications#33]
social media copy PR : https://github.com/pyladies/project-communications/pull/38

**Comment by Marie-L** [comment]
@AbigailDogbe, can we use the same copy for the Pyladies blog on Python Software Foundation blog too ?

**Comment by AbigailDogbe** [comment]
Yes i think so. We surely can.

**Comment by Marie-L** [comment]
by @AbigailDogbe 
![Red Women's Beauty Facebook Post](https://user-images.githubusercontent.com/27898533/76116175-709f7480-5fe1-11ea-8d2f-d09c607cce57.png)

**Comment by Marie-L** [comment]
updated version : 
![PyLadies notice (4)](https://user-images.githubusercontent.com/27898533/76122641-73549680-5fee-11ea-9057-c83e07799c82.png)

**Comment by Marie-L** [comment]
> Yes i think so. We surely can.

@AbigailDogbe ok great, @lorenanicole how can we access the PSF blog to make the announcement ?

**Comment by Marie-L** [comment]
this issue has now been completed
