### ISSUE TITLE
Request to Join Project Communications: @voru588

### ISSUE THREAD

**Issue by voru588** [pyladies/project-communications#4]
_This template should be used (edited) for PyLadies members that wish to join the Project Communications team.

**Proposed Team Member Details**

Name | GitHub Handle | PyLadies Chapter | Team Role 
| Alena | @voru588 | PyLadies Paris | Member

**Why do you want to join the PyLadies Project Communications team?**
Hello everyone,
I am from Paris chapter and I would like to help. 
I am still pretty new to Python (only about a year), but keep working on my skills and try to improve every day. I was very excited to find your community and would like to meet new friends with the same love for data.
I hope I can be useful to you)))
[Alena](https://www.linkedin.com/in/alenavorushilova/)
/cc @pyladies/communications

**Comment by lorenanicole** [comment]
@AbigailMesrenyameDogbe I added you onto this issue as you are helping co-lead this project team.

**Comment by Caaddss** [comment]
Hi @voru588 do you on the Pyladies Slack??

**Comment by voru588** [comment]
Hi @Caaddss , Yes, I am. I joined yesterday)

**Comment by Caaddss** [comment]
@lorenanicole she participated with us yesterday...could you invite her to team, please?

**Comment by lorenanicole** [comment]
@voru588 adding you momentarily. Please look in your inbox for an invite to the PyLadies Comms Team - https://github.com/orgs/pyladies/teams/communications.
