### ISSUE TITLE
Request to Join Project Communications: Kittylon

### ISSUE THREAD

**Issue by kittylon** [pyladies/project-communications#42]
_This template should be used (edited) for PyLadies members that wish to join the Project Communications team.

**Proposed Team Member Details**

Name | GitHub Handle | PyLadies Chapter | Team Role 
| Carolina Londoño| Kittylon| Amsterdam| Member

**Why do you want to join the PyLadies Project Communications team?**
Because I want to encourage woman around the globe to be accomplished in their career, I know sometimes it's hard and I want to be available for answering questions and mentoring them and also learn and grow in the process. I share my values and mission with PyLadies and ever since I learned from this community I've been involved, starting in Medellin's chapter and now in Amsterdam's, but I am no longer an organizer, therefor being a contributor of the project communication is a great way to be involved and keep the community alive on the internet.
/cc @pyladies/communications

**Issues or projects that I'm interested in helping out with**
#10 
#18 
#29  

**Time zone**
CET

**Languages I speak**

|Language | Level |
|Spanish| Native |
|English | Advanced|

**Are you comfortable communicating in English?**
Yes

**Monthly meetings**: Are you available to attend conference calls once a month? 
yes
- _NOTE:team members must be available for a monthly video call_

**Involvement** : How frequently can you contribute to the team?
- _NOTE: Team members are required to be active during a 3 month period (involvement is defined below):_
_1. submitting a PR or review_ 
_1. attending one or more meetings in a three month period_
_1. making progress on an assigned issue_

**Comment by Marie-L** [comment]
@kittylon Thank you for submitting your request! @lorenanicole, when you have time can you please add her to the repo ?

**Comment by lorenanicole** [comment]
@kittylon done!
