### ISSUE TITLE
Monthly Comms Team Meeting: May 8th & 15th 2020

### ISSUE THREAD

**Issue by Marie-L** [pyladies/project-communications#48]
## Monthly Comms Team Meeting

**Attendees:**
- @Marie-L 
- @AbigailDogbe 
- @lorenanicole 
- @BethanyG 
- @albendz 
- @kittylon 

**Date:**
- May 8th & May 15th 2020

**Previous meeting issue link:**

- #47 

### Agenda
_Please add items as needed. If you add a topic please make sure to attend the meeting._

**Topic for discussion** | **Sub Topic** | **Notes** | **Action points** | **Person Responsible** | 
-- | -- | -- | -- | --
 PyLadies Global Election 2020|PyLadies Global Council Election 2020 Comms Strategy |**We need to remind people that they need to vote (we can use google docs for blog posts drafts and @AbigailDogbe can help)**,There will be a form to self nominate) then go to the link to apply or nominate yourself, **MUST ADD LINK TO GENERAL ELECTION SITE** , we must nudge people to get voting privileges and also to participate| Comms team member will be @AbigailDogbe & @Marie-L point of contact people to work with Global interim team (@lorenanicole), Develop Comms Strategy,  Publish content (for now on old blog of website) with Global Interim team (Debora Azevedo) for translation Coordinate, Find out more about global Election 2020 - **TO DO THIS MONTH: Break down issue into epic** | @lorenanicole (point of contact with election), TODO: @Marie-L & @AbigailDogbe will continue to work toward producing content according to the schedule, **DEADLINE:** May 15th, 
|Onboarding | | | | |
 ||PyLadies code of conduct |||@Marie-L **COMPLETED** but need to make a PR to update - in future there could be a blog post to document the process 
 | |Pending requests to join & intake dates || @Marie-L must ask @kittylon to make new request |@Marie-L
 | User manual for me| As the LAST part of onboarding this will be worked on until the end of the month | | |@Marie-L remind @kittylon, @BethanyG 

## Sprint Planning
 - @Marie-L #36 #3 #1 #45 
- @AbigailDogbe #36 
- @kittylon #10 #18 #29 #1 
- @albendz will open tickets in the infra repo and keep us updated

## Next Meeting:
TBC

cc / @pyladies/communications

**Comment by albendz** [comment]
Task opened in infra repo: https://github.com/pyladies/pyladies/issues/475
