### ISSUE TITLE
find out whether processes for contributing have been documented

### ISSUE THREAD

**Issue by Marie-L** [pyladies/project-communications#6]
Question: How do we write, review, and publish new blog posts?

Looking for existing documentation on blog management or blog publishing.

**Comment by albendz** [comment]
@lorenanicole Do you know where the pyladies blog accounts/documentation exists if at all?

**Comment by lorenanicole** [comment]
The old PyLadies blog (what is found on pyladies.com) has info in the main PyLadies GitHub repo in the README here - https://github.com/pyladies/pyladies#to-contribute-to-the-repository which points to https://github.com/pyladies/pyladies/blob/master/CONTRIBUTING.md.

Is that what you wanted @albendz ?

**Comment by Marie-L** [comment]
@lorenanicole thanks for the links !

**Comment by albendz** [comment]
Yes! Thank you @lorenanicole . I will add these links in our docs and then close this issue with that MR.
