### ISSUE TITLE
Twitter avatar

### ISSUE THREAD

**Issue by Marie-L** [pyladies/project-communications#63]
**Summary**

We're looking into how we can update our social media avatars in a way that reflects our diversity. Further to a suggestion made by @econchick :

> it’d be cool to have a script that changes the twitter profile image daily with each chapter’s design

We will work towards implementing this idea using zapier

**Acceptance Criteria**

1.  chapter _geek-girl_ files (re-sized)
1.  integrate zapier _'update twitter profile pic'_ action

**Do you want to work on this issue (Yes/No)?**

Yes, with @Mariatta and all help is welcome

cc / @pyladies/communications

**Comment by Marie-L** [comment]
I'll create a table with the info and will share it here @Mariatta

**Comment by Marie-L** [comment]
@Mariatta here are a few urls: [chapter avatar](https://docs.google.com/spreadsheets/d/1-PPQ0Su3kRsxOEod7wD6xfXbcpC8fOkFbrdVqpt_NpI/edit?usp=sharing). I will keep updating it until it contains them all. Please let me know if you need anything else

**Comment by BethanyG** [comment]
@Marie-L   Happy to help -- just let me know the steps/where to put images/what you need.  😄

**Comment by Marie-L** [comment]
Thanks @BethanyG 😊 ! @Mariatta, when you have time can you please share the method so we can get started on setting this up 😊?

**Comment by Mariatta** [comment]
Yeah I will be doing this using Zapier. Perhaps we can set up a Zoom call where I can show how do it within Zapier? I'm quite open on Friday this week.

**Comment by Mariatta** [comment]
Instead of google sheets, I think it is easier to have the list of avatars as a csv file. I've created the csv in #66.

**Comment by BethanyG** [comment]
I have a meeting 9-11 on Friday 7/30 - but am free earlier/later, if you want to do a call @Mariatta @Marie-L.

**Comment by Marie-L** [comment]
@Mariatta thanks for creating a csv! Yes, I'm available on Friday, what time are you thinking ?

**Comment by Mariatta** [comment]
Would tomorrow, Friday 11 AM PDT/7 PM GMT work? I've sent you both Slack DM so I can send out calendar invite. @BethanyG @Marie-L

**Comment by Mariatta** [comment]
I can also do 8 AM PDT / 3 PM GMT if that would work better for you all.

**Comment by BethanyG** [comment]
Either time works for me @Mariatta!  @Marie-L  - which time works best for you?

**Comment by Marie-L** [comment]
8am PDT / 4pm BST is good for me @BethanyG @Mariatta , thanks !

**Comment by Mariatta** [comment]
Today we set up the automation using Zapier to update the avatar daily, and we also added the step to post a tweet about the new profile picture. Other suggested improvements to this are:
- add a column with link to the PyLadies chapter website/meetup so we can include it on the tweet
- add a column with the PyLadies twitter account so we can @-mention them on twitter
- some logo may need to be resized for twitter
- add more logos

**Comment by hugovk** [comment]
It's working really well!

https://twitter.com/pyladies/status/1293412110664425473

> #NewProfilePic Today we feature PyLadies Saint Petersburg, Russia pyladies_spb as our avatar. Check out their website: https://t.co/kshcpQ0T07 https://t.co/KgevJY3AaR

@Mariatta Is it possible to put an `@` before the Twitter handle?

**Comment by Mariatta** [comment]
Unfortunately we can't @ mention on twitter user using Zapier. I've added it, but it got automatically removed. ☹️ 

![Screen Shot 2020-08-12 at 10 07 56 AM](https://user-images.githubusercontent.com/5844587/90045411-daeccd00-dc83-11ea-90f0-f771d7106e43.png)

https://zapier.com/help/doc/common-problems-twitter#symbols-are-being-stripped-from-posts

**Comment by Marie-L** [comment]
This is now complete so I will close the issue.
