### ISSUE TITLE
"Meet PyLadies" Interview Video Series

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/project-communications#68]
**Summary**

# Proposal

Interview PyLadies members focusing on the following for a multilingual series called, "Meet PyLadies: We present ____":

The intent is to:

- Highlight global community members
- Better tell the story of who PyLadies are and what we do
- Provide opportunities for global members to participate in another volunteer opporunity

## Format

The interview will be between 15 to 25 minutes in length and hosted on PyLadies YouTube account, Facebook Live, and Instagram with StreamYard. 

## Content

Questions will be based on some subset of the following:

1. What is your name and your pronouns?
2. Where are you based?
3. How did you join the tech space? 
4. Tell us about how you joined PyLadies! Are you a member of a chapter? An organizer?
5. What else do you do in the Python and broader open source community?
6. What would you like to be doing a year from now?
7. Close with something fun -- what is your favorite Python tip, trick or tool? 
8. Anything else you'd like to plug? Where can we find you?

## Sourcing Interviews and Interviewers

Create a workflow (e.g. Google form) where PyLadies members can request to be interviewed or request to be the interviewer! We'll want to target members from various countries and languages.

## Review

We should try to have some baseline review of content to ensure there are no violations of our Code of Conduct. Perhaps working with our `#project-translation` in Slack to have folks listen and sign off that the content is good can be an added step.  

## Work in Progress

@lorenanicole has scheduled the following to start:

- Interview with PyLadies Cochabomba organizer Carlita M F Roman - Sept 4th @ 20:00 CDT (Spanish, Bolivia)
- Interview with PyLadies Chicago / SF member Sree P. - August 9th @ 14:00 CDT (English, USA) - Done
- Interview with PyLadies Hamburg organizer Tereza - Aug 2020 (English, Germany) -  Done
- Interview with PyLadies Mexico organizer Mayela - Aug 2020 (Spanish, Mexico) - Done
- Interview with PyLadies Bangkok organizer Georgi Ker - WIP (English, Thailand)

## Project Owner

@lorenanicole 

**Acceptance Criteria**

## Resources Needed from Project Comms

- Workflow to source interviews (e.g. google form)
- Reusable images for branding (e.g. placard for Instagram, YouTube, Facebook with PyLadies logo and "Meet PyLadies: Presenting ____" and drop in image) that are localized 
- StreamYard account (@lorenanicole currently using personal) can be shared with Comms team 

**Do you want to work on this issue (Yes/No)?**

cc / @pyladies/communications

**Comment by Marie-L** [comment]
This is such a great idea @lorenanicole ! I can aim to produce version 1 (we can continue to iterate and improve as we go) branding images  as well as creating a StreamYard account for the comms team by sunday morning - before the 2nd interview, then work on creating a workflow next week. What do you think ?

**Comment by Marie-L** [comment]
YT Thumbnail test
![meet_pyladies_thumbnail_test](https://user-images.githubusercontent.com/27898533/89721263-77d50f00-d9d3-11ea-8c63-1228da2f5c0f.png)

**Comment by Marie-L** [comment]
Social promo test 
![insta_meet_pyladies_test](https://user-images.githubusercontent.com/27898533/89721271-9affbe80-d9d3-11ea-9f9c-bbfdbb7d2ff8.gif)

**Comment by Marie-L** [comment]
@lorenanicole In the process of setting up streamYard acc, but don't have login credentials for comms email. When you have time can you please share them with me? Thanks !

**Comment by lorenanicole** [comment]
I just saw these assets! These are great!

**Comment by drcat101** [comment]
I'd like to sign up to do one of these as an interviewer, and I have found an interviewee - Aseda from PyLadies Ghana. Let me know what are the next steps :)

**Comment by Marie-L** [comment]
![AMA Youtube Thumbnail](https://user-images.githubusercontent.com/27898533/91311535-1a9ad500-e7ab-11ea-8dc6-4d1e2b9a79b2.png)

**Comment by Marie-L** [comment]
![AMA_insta](https://user-images.githubusercontent.com/27898533/91311680-43bb6580-e7ab-11ea-802f-5d9d157be303.gif)

**Comment by Marie-L** [comment]
![AMA_insta](https://user-images.githubusercontent.com/27898533/91311781-5fbf0700-e7ab-11ea-95fa-b9abdaedc2d6.png)

**Comment by deboraazevedo** [comment]
@Marie-L is there anyway I can find the svg file from these last images?

**Comment by Marie-L** [comment]
@deboraazevedo, I'll add them to my g drive and share them with you

**Comment by Marie-L** [comment]
@deboraazevedo it's done, please let me know if you haven't received the invitation 😊

**Comment by deboraazevedo** [comment]
@Marie-L I received it, thank you!

**Comment by Marie-L** [comment]
@deboraazevedo ok great, you're welcome !

**Comment by cecivieira** [comment]
@Marie-L Could you send us one of this images in svg format (vector format)?
On friday we'll make a portuguese version with @deboraazevedo , so we need create a thumbnail to youtube. I'm glad if you can share the svg (vector) with us

**Comment by Marie-L** [comment]
@cecivieira Unfortunately, the program I used doesn't have the option to export them in svg format. Therefore, I will need to use adobe illustrator in order to convert them. When do you need the images by ?

**Comment by Marie-L** [comment]
@cecivieira it could be easier if you send me the portuguese copy and I'll create new ones for you. Let me know

**Comment by BethanyG** [comment]
@Marie-L   -- couldn't we invite them to Canva, and have them edit there?  Or are these not in Canva.  Also -- if you need help, I can also use Affinity to convert these to SVG...just let me know.  I can also help with copy versions.

**Comment by cecivieira** [comment]
@Marie-L Which options to editable format are available in your program?
The Inkscape can import AI, EPS, CDR...

**Comment by cecivieira** [comment]
@Marie-L @lorenanicole 

The informations about the episode at 20th Sept. of "Meet PyLadies":

(en)
As a part of our "Meet PyLadies" series we will have a chat with PyLadies Recife member Anyceli Santos, a software developer and social activist based in Ipojuca - PE(BR). Working at Ipojuca’s City Hall, she is a enthusiastic of community works and loves play pagode and samba.

Twitter: https://twitter.com/shuri_any

---------
(pt-br)
Nesse episódio do "Mett PyLadies" vamos conversar com a membra da PyLadies Recife Anyceli Santos. Ela é engenheira de software e ativista social, mora em Ipojuca - PE e trabalha na prefeitura da sua cidade de residência. É uma entusiasta de iniciativas sociais contruidas coletivamente e ama tocar pagode e samba.

Twitter: https://twitter.com/shuri_any

![image](https://user-images.githubusercontent.com/30605862/91439652-bb3cd380-e843-11ea-8532-7dceadfc69ac.png)

**Comment by lorenanicole** [comment]
We've got an EXTRA SPECIAL session tomorrow @Marie-L and @AbigailDogbe !! 

There'll be *two* interviews with Karo (spanish) and Valery (english) with Diana as the interviewer!

Event title: "Conoce PyLadies: Presentamos Valery Briz (in English) & Karo Ladino (en español)"
Date: Friday August 27 @ 19:00 CDT
Link: https://www.youtube.com/watch?v=jaPKZGfi-HU

Pictures 👇 
 
![New Karo](https://user-images.githubusercontent.com/4573607/91466970-82a5f580-e855-11ea-87fb-cd7110516bf2.jpg)
![valery](https://user-images.githubusercontent.com/4573607/91466980-85a0e600-e855-11ea-9ba1-0733fc1fb3ec.jpeg)

Bios 👇 

Diana Rodríguez is a web developer, infrastructure and automation specialist with over 20 years’ experience in the tech ecosystem. Strong in community presence, she leads GDG Durham and PyLadies RDU. Diana is a Google Developers Expert in Web, Cloud, Maps and Firebase, Auth0 and Women Techmakers ambassador, Microsoft MVP and Python Software Foundation contributing member. Diana loves connecting people with opportunities.

Valery Briz is a Senior Data Engineer at Fairplay, writer at Cloud Academy, Telecommunications Engineer. Pythonista, Co-organizer of PyLadies CDMX, Founder of the Python community in Guatemala, speaker in multiple Pycon's and PyLatam 2020-2021 Co-organizer.

Karo es ingeniera en robótica hardware hacker y maker. Es profesora de universidad y digital. Lidera PyLadies Bogotá y Women in Data Science Bogotá. Hace parte de Python Colombia y es co-organizadora de PyConCo. Tiene más de 6 años creando hardware para diferentes tipos de disciplinas. Ama trabajar en pro de crear oportunidades y espacios para el crecimiento personal y profesional de las personas.

**Comment by lorenanicole** [comment]
Annnnd another!

Title: "Conoce PyLadies: Presentamos Carla Florida"
Who: Carla Florida
Date: September 4 2020 @ 20:00 CDT
 
Photo 👇 

![image](https://user-images.githubusercontent.com/4573607/91489021-c577c580-e875-11ea-97e4-79a6282f7662.png)

Bio 👇 

Carla Florida is completing her studies in System Engineering. She is active in local and international Machine Learning and Data Science communities. Carla leads the community "Pyladies Cochabamba," and she was awarded the prestigious Grace Hopper Celebration scholarship. She is as well a Cisco Networking Academy instructor. Her general areas of interest are Machine Learning and Deep Learning. Carla supports our group as an Associated Research Engineer developing state-of-the-art deep learning models for Conversational AI.

**Comment by Marie-L** [comment]
@cecivieira thanks for sharing info for the _'Meet PyLadies'_ episode with Anyceli Santos, we're currently working on the artwork so will keep you updated

**Comment by Marie-L** [comment]
@BethanyG Thanks for your suggestions and help !

**Comment by Marie-L** [comment]
@lorenanicole for tonight's episode :
![insta_conoce_pyladies_valery_ _karo](https://user-images.githubusercontent.com/27898533/91593032-5c687e80-e957-11ea-80f6-75d91c2b225c.gif)
![conoce_pyladies_thumbnail_valery_ _karo_es](https://user-images.githubusercontent.com/27898533/91593049-61c5c900-e957-11ea-98fe-2f8becfd214b.png)

- I've made versions in both languages
- Please correct my spanish i.e ("entrevistado por" / "interviewed by") etc.
- I couldn't include the languages "Valery Briz **(in English)** & Karo Ladino **(en español)**" because there wasn't enough space, so will need to add that into the copy when it's posted. Please let me know if that's ok
- also I added the unofficial tagline (taken from your proposal) (" Highlighting global community members" / "Destacar a los miembros de la comunidad global"), what do you think ?

any feedback will be much appreciated

**Comment by Marie-L** [comment]
![insta_meet_pyladies_valery_ _karo](https://user-images.githubusercontent.com/27898533/91594017-17454c00-e959-11ea-81c9-c7250f809dd3.gif)
![meet_pyladies_thumbnail_valery_ _karo_en](https://user-images.githubusercontent.com/27898533/91594028-1c0a0000-e959-11ea-9fdf-a44c49445609.png)

**Comment by AbigailDogbe** [comment]
Blog Post Alert!

Hello PyLadies, our next "Meet PyLadies" event is here again!

There'll be two interviews with **Karo Ladino** (in spanish) and **Valery Briz** (in english) with **Diana Rodríguez** as the interviewer!

Our interviewer is a web developer, infrastructure and automation specialist with over 20 years’ experience in the tech ecosystem. Strong in community presence, she leads GDG Durham and PyLadies RDU. She is a Google Developers Expert in Web, Cloud, Maps and Firebase, Auth0 and Women Techmakers ambassador, Microsoft MVP and Python Software Foundation contributing member. Diana loves connecting people with opportunities.

Karo Ladino es ingeniera en robótica hardware hacker y maker. Es profesora de universidad y digital. Lidera PyLadies Bogotá y Women in Data Science Bogotá. Hace parte de Python Colombia y es co-organizadora de PyConCo. Tiene más de 6 años creando hardware para diferentes tipos de disciplinas. Ama trabajar en pro de crear oportunidades y espacios para el crecimiento personal y profesional de las personas.

Finally, Valery Briz is a Senior Data Engineer at Fairplay, writer at Cloud Academy, Telecommunications Engineer. Pythonista, Co-organizer of PyLadies CDMX, Founder of the Python community in Guatemala, speaker in multiple Pycon's and PyLatam 2020-2021 Co-organizer.

**Date:** Friday August 27 @ 19:00 CDT
**Link:** https://www.youtube.com/watch?v=jaPKZGfi-HU

Don't miss this fun and interactive session, as we highlight global community members.
Cheers and see you there!

**Comment by Marie-L** [comment]
@AbigailDogbe This is great, thanks! when can we get in posted to the blog ?

**Comment by AbigailDogbe** [comment]
I'm not sure but I think we can put them on our social media platforms for now. That is if it is ready to go.

**Comment by lorenanicole** [comment]
LGTM! :shipit:

**Comment by Marie-L** [comment]
ok great! i'll post on socials at 21:00 BST

**Comment by Marie-L** [comment]
final copy for twitter :

Join us for the next episode of "Meet @PyLadies" tonight 19:00 CDT! There'll be two interviews with @karobotco (in Spanish) and @valerybriz (in English) with Diana Rodríguez as the interviewer! See you there! https://www.youtube.com/watch?v=jaPKZGfi-HU 

Hola! Tenemos el próximo episodio de "Conoce a @PyLadies" hoy a las 19:00 CDT!  Habrá dos entrevistas con @karobotco (en español) y @valerybriz (en inglés) con Diana Rodríguez como entrevistadora! Los esperamos! https://www.youtube.com/watch?v=jaPKZGfi-HU

**Comment by cecivieira** [comment]
@Marie-L the 'Meet PyLadies' episode with Anyceli Santos will be at 20th Sep. Is the art ready?
@lorenanicole how could I get the StreamYard and Youtube link? Could we start promote the episode?

**Comment by AbigailDogbe** [comment]
Hello @cecivieira can you please point me to her photograph and bio?

**Comment by cecivieira** [comment]
> @Marie-L @lorenanicole
> 
> The informations about the episode at 20th Sept. of "Meet PyLadies":
> 
> (en)
> As a part of our "Meet PyLadies" series we will have a chat with PyLadies Recife member Anyceli Santos, a software developer and social activist based in Ipojuca - PE(BR). Working at Ipojuca’s City Hall, she is a enthusiastic of community works and loves play pagode and samba.
> 
> Twitter: https://twitter.com/shuri_any
> 
> (pt-br)
> Nesse episódio do "Mett PyLadies" vamos conversar com a membra da PyLadies Recife Anyceli Santos. Ela é engenheira de software e ativista social, mora em Ipojuca - PE e trabalha na prefeitura da sua cidade de residência. É uma entusiasta de iniciativas sociais contruidas coletivamente e ama tocar pagode e samba.
> 
> Twitter: https://twitter.com/shuri_any
> 
> ![image](https://user-images.githubusercontent.com/30605862/91439652-bb3cd380-e843-11ea-8532-7dceadfc69ac.png)

@AbigailDogbe here

**Comment by AbigailDogbe** [comment]
Thank you

**Comment by AbigailDogbe** [comment]
@cecivieira what time will this event happen?

**Comment by cecivieira** [comment]
@AbigailDogbe 15:00 (GMT -3)

**Comment by AbigailDogbe** [comment]
![meet_pyladies_thumbnail_Anyceli Santos_en](https://user-images.githubusercontent.com/29455771/93319347-4ab02380-f7ff-11ea-9c77-ba78216adb57.png)

**Comment by Marie-L** [comment]
Thanks for your help @AbigailDogbe ! @cecivieira sorry I haven’t had the chance to get back to you. The version posted above is unfinished. We will send you the final version by Friday

**Comment by cecivieira** [comment]
@Marie-L @AbigailDogbe The interview will be in portuguese, so maybe it's a good idea informs it in the art.
Besides that, could you make a portuguese version?

**Apresentamos:
Anyceli Santos
Domingo, 20 set.
15:00 (GMT-3)**

**Comment by AbigailDogbe** [comment]
Absolutely, this can be done.

**Comment by Marie-L** [comment]
@cecivieira I'm sorry I haven't had the chance to finish the graphics, can you please wait until tomorrow ?

**Comment by cecivieira** [comment]
@Marie-L @lorenanicole could we reschedule to 18th Oct. at 15:00 (GMT -3)?
So we have time to publish in our social media and invite more women to watch the interview.

**Comment by lorenanicole** [comment]
@Marie-L if you need help let me know!

**Comment by Marie-L** [comment]
ok will do, thanks @lorenanicole !

**Comment by cecivieira** [comment]
@Marie-L @lorenanicole Could you send me the graphics until 10th Oct?
The interview will be in portuguese, so maybe it's a good idea informs it in the art.
Also, could you make a portuguese version?

Apresentamos:
Anyceli Santos
Domingo, 20 set.
15:00 (GMT-3)

**Comment by Marie-L** [comment]
Hi @cecivieira, I'm sorry I can't send them by the 10th Oct, but will do during the following week. Thanks !

**Comment by AbigailDogbe** [comment]
Hello @Marie-L is there anything particualar you need to do about the flyer? I could help so we can have it done before 10th.

**Comment by Marie-L** [comment]
Thanks for your offer of help @AbigailDogbe 🙏. @cecivieira we are working towards getting more collaboration regarding producing graphics so in future you will be able to access the assets and edit them yourself as and when needed. But for now we'll do our best to get them to you by the start of next week. Thank you for your patience 🙂

**Comment by Marie-L** [comment]
Hi @cecivieira, here's the [YT link](https://www.youtube.com/watch?v=-b-drE-aZF4&feature=youtu.be) and also the graphics: 
![insta_meet_pyladies_Anyceli Santos](https://user-images.githubusercontent.com/27898533/95728205-2535fe80-0c73-11eb-9523-b04255349d59.png)
![insta_meet_pyladies_Anyceli Santos](https://user-images.githubusercontent.com/27898533/95728222-2a934900-0c73-11eb-94e3-0a2755b6bc7c.gif)
![insta_meet_pyladies_Anyceli Santos_pt](https://user-images.githubusercontent.com/27898533/95728228-2bc47600-0c73-11eb-9d65-970f607de083.gif)
![insta_meet_pyladies_Anyceli Santos_pt](https://user-images.githubusercontent.com/27898533/95728242-2f57fd00-0c73-11eb-80ea-4f6d6f88d3ed.png)

Please let me know if anything needs changing. 

Also, it would be great to schedule a chat with you and all those involved in order to prepare. Please contact me on slack with your availability. Thanks 🙂 !

**Comment by cecivieira** [comment]
@Marie-L Thank you!!!!!!!!!

**Comment by Marie-L** [comment]
@cecivieira no problem 😉! Please find the updated versions below: 
![insta_meet_pyladies_Anicely_Santos_pt](https://user-images.githubusercontent.com/27898533/96111894-bd352180-0ed9-11eb-8642-2642cf52e0a6.gif)
![insta_meet_pyladies_Anicely_Santos_pt](https://user-images.githubusercontent.com/27898533/96111906-c1613f00-0ed9-11eb-880a-3c1d2a47308a.png)
![insta_meet_pyladies_Anicely_Santos](https://user-images.githubusercontent.com/27898533/96111924-c4f4c600-0ed9-11eb-9aa5-5633c9562976.gif)
![insta_meet_pyladies_Anicely_Santos](https://user-images.githubusercontent.com/27898533/96111928-c6be8980-0ed9-11eb-8156-f9a617b13e76.png)
![meet_pyladies_thumbnail_Anicely_Santos_en_1](https://user-images.githubusercontent.com/27898533/96111932-c8884d00-0ed9-11eb-9f01-d6ab6487a387.png)

Please let me know if there are anymore changes to be made 🙂

**Comment by cecivieira** [comment]
Thank you @Marie-L !!!!

**Comment by Marie-L** [comment]
you're welcome @cecivieira 😊
