### ISSUE TITLE
Write use cases & user stories

### ISSUE THREAD

**Issue by Marie-L** [pyladies/project-communications#7]
### **Use Cases**
_NOTE: these are the main ones identified but we can add more (or include more details) in future _ . For more info on [Use cases](https://www.usability.gov/how-to-and-tools/methods/use-cases.html) and [User stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Use Case** |Access about page  | 
-- | --
**Actor** | User
**Trigger** | The user discovers the link in the nav bar after arriving on the landing page
**Basic Flow** | sees _About_ link and clicks

**Use Case** |Access Locations page  | 
-- | --
**Actor** | User
**Trigger** | The user discovers the link in the nav bar after arriving on the landing page
**Basic Flow** | sees _Locations_ link and clicks

**Use Case** |Access Resources page  | 
-- | --
**Actor** | User
**Trigger** | The user discovers the link in the nav bar after arriving on the landing page
**Basic Flow** | sees _Resources_ link and clicks

**Use Case** |Access Blog page  | 
-- | --
**Actor** | User
**Trigger** | The user discovers the link either in the nav bar or when scrolling down the  landing page 
**Basic Flow** | sees _Blog_ link and clicks

**Comment by BethanyG** [comment]
@Marie-L  I can (maybe) help with this.

**Comment by Marie-L** [comment]
@BethanyG yes please, if you have time 😊
