### ISSUE TITLE
Broadcasting a virtual event to the PyLadies YouTube channel

### ISSUE THREAD

**Issue by maud-lv** [pyladies/project-communications#71]
Broadcasting a virtual event to the PyLadies YouTube channel: https://www.youtube.com/channel/UCs0-1JQdb1YkVxN4hnNKsNQ 

**Summary**

I would like to broadcast a Hacktoberfest meetup organized by the PyLadies Paris team, to the PyLadies YouTube channel: https://www.youtube.com/channel/UCs0-1JQdb1YkVxN4hnNKsNQ. Any PyLadie meetup orgaziner is welcome to join the team to make this a bigger event.

Event is on October 1:
6:00-6:10PM Introduction
6:10-6:30PM Why contribute to Open Source?
6:30-6:50PM Open Source in Scientific Research
6:40-7:00PM How to make your first contribution: step by step demo
7:00-7:30: Project contribution ideas
7:30-End of October: work on Slack

I have done several live shows on YouTube before. I use Streamyard which I connect to YouTube in order to broadcast the event with several speakers who are able to interact live with participants (participants write in the chat).

**Acceptance Criteria**

cc / @pyladies/communications

**Comment by Marie-L** [comment]
Hi @maud-lv, thank you for submitting this ! Will you be presenting ? Also, will this be a bilingual event ?

**Comment by maud-lv** [comment]
Hi @Marie-L the event will be in English only. I will probably do the MC with Maria, one of the PyLadies Paris organizer. Speakers will include Chiara Marmo, Lucy (the third PyLadies organizer) and Yohan Lasorsa. If you or someone else from your team would like to join to present something or host the show with us let me know.

**Comment by maud-lv** [comment]
Hello @Marie-L here is the full schedule - do you think I could get a reply today? If that's not possible we will create a YouTbue account just for PyLadies Paris. Thank you!

6:00-6:10PM Introduction
6:10-6:30PM Why contribute to Open Source? by Yohan Lasorsa 
6:30-6:50PM Open Source to Open Research by Chiara Marmo
6:40-7:00PM How to make your first contribution: step by step demo by @Laïla Atrmouh
7:00-7:15PM: What to look for in a project to contribute to? by Jennifer Davis
7:15-7:30: Project contribution ideas
7:30-End of October: work on Slack

**Comment by Marie-L** [comment]
Hi @maud-lv, my apologies for the delay! Thanks for providing more information. You are welcome to broadcast this on the main pyladies youtube channel. Please let me know if you are still interested. Thanks

**Comment by Marie-L** [comment]
@maud-lv here's the [link](https://www.youtube.com/watch?v=uXE1Wc6blDA)

**Comment by Marie-L** [comment]
I know you already have artwork but I needed to create a thumbnail, so I also made one to post on our socials. Please let me know if there are any issues before I post tomorrow morning
![Pyladies_paris_hacktoberfest_thumb](https://user-images.githubusercontent.com/27898533/94743296-0da36f80-036f-11eb-9cd5-ac7e9146c8ac.png)
![Pyladies_paris_hacktoberfest_insta](https://user-images.githubusercontent.com/27898533/94743305-12682380-036f-11eb-9b06-2c31f6d56f22.png)
![Pyladies_paris_hacktoberfest_insta](https://user-images.githubusercontent.com/27898533/94743372-2d3a9800-036f-11eb-88fd-fd03cf742f92.gif)

**Comment by Marie-L** [comment]
![Pyladies_paris_hacktoberfest_insta](https://user-images.githubusercontent.com/27898533/94745608-f49cbd80-0372-11eb-8924-f77ca19bce44.png)
![Pyladies_paris_hacktoberfest_insta](https://user-images.githubusercontent.com/27898533/94745615-f797ae00-0372-11eb-9366-823815be300d.gif)

**Comment by Marie-L** [comment]
@maud-lv updated :
![Pyladies_paris_hacktoberfest_thumb](https://user-images.githubusercontent.com/27898533/94803046-97d7ec00-03e0-11eb-85df-92e85404fc88.png)
![Pyladies_paris_hacktoberfest_insta](https://user-images.githubusercontent.com/27898533/94803053-9a3a4600-03e0-11eb-9420-b8d5167dd230.png)
![Pyladies_paris_hacktoberfest_insta](https://user-images.githubusercontent.com/27898533/94803058-9c9ca000-03e0-11eb-899f-da1928ca7fb1.gif)

**Comment by maud-lv** [comment]
I love it!

**Comment by Marie-L** [comment]
This is complete, so I will close the issue
