### ISSUE TITLE
PyLadies Auction promo

### ISSUE THREAD

**Issue by Marie-L** [pyladies/project-communications#76]

**Comment by Marie-L** [comment]
![PyLadies_auction_pycon](https://user-images.githubusercontent.com/27898533/108001096-7704e180-6fe3-11eb-9cee-5de8a8df2789.png)

**Comment by Marie-L** [comment]
![PyLadies_auction_pycon (1)](https://user-images.githubusercontent.com/27898533/108001250-cfd47a00-6fe3-11eb-8ef3-0a3da8c6a6a5.gif)

**Comment by Marie-L** [comment]
![PyLadies_auction_pycon (3)](https://user-images.githubusercontent.com/27898533/108001637-e0d1bb00-6fe4-11eb-9b2c-94bdce5ab29c.gif)

**Comment by Marie-L** [comment]
@lorenanicole @kittylon @BethanyG @julianafalves @cecivieira I'd like to start posting these this week so have started drafting the copy (based off an old auction promo tweet I found) :

_We are proud to announce that the 10th Annual PyLadies Auction at #PyCon2021 will be held virtually !  A crowd favorite filled with fun, charity and competition !

More details here: https://us.pycon.org/2021/events/auction/

Space is limited and demand is high – add your ticket to your registration today! https://us.pycon.org/2021/registration/information/_ 


Please share your feedback and ideas. Thanks !

**Comment by lorenanicole** [comment]
> Space is limited and demand is high – add your ticket to your registration today! https://us.pycon.org/2021/registration/information/

Is space limited now in the virtual moment? I haven't been able to make the last few auction planning meetings, @econchick could you confirm if there is an upper cap?

**Comment by Marie-L** [comment]
@lorenanicole good point ! I'll remove that part, thanks !

**Comment by Marie-L** [comment]
I will confirm the times (and any other details) at tomorrow's meeting before posting

**Comment by Marie-L** [comment]
UPDATE:

_We are proud to announce that the 10th Annual PyLadies Auction at #PyCon2021 will be held virtually ! A crowd favorite filled with fun, charity and competition ! Add your ticket to your registration today! https://us.pycon.org/2021/registration/information/

More details here: https://us.pycon.org/2021/events/auction/ #PyLadies_

**Comment by kittylon** [comment]
Hi @Marie-L 

Is it ok to post now?
To confirm the dates in the canvas image:

may 8th  15th 2021 19:00 ET

**Comment by Marie-L** [comment]
Hey @kittylon, I still need to confirm some details. Can you please wait until I update this issue with the updated graphics etc ? Thanks 😊

**Comment by kittylon** [comment]
Sure I will wait for your confirmation :)

**Comment by Marie-L** [comment]
![PyLadies_auction_pycon (4)](https://user-images.githubusercontent.com/27898533/114612065-8fb70e00-9c99-11eb-86a0-4aa23524bb7a.gif) 
![PyLadies_auction_pycon (1)](https://user-images.githubusercontent.com/27898533/114612392-fccaa380-9c99-11eb-9590-9ddd53e62116.png)

@kittylon Here are the most up-to-date graphics, but I'm still waiting for some stats for the caption so can you please wait a bit longer ? Thanks for your help 🙏

**Comment by kittylon** [comment]
Hello,

can I still post with without the stats?

**Comment by Marie-L** [comment]
Hey @kittylon, sorry I've just seen your last comment. I've got that stats now but I'm not sure if I should share it on github so I'll email it to you instead

**Comment by Marie-L** [comment]
copy UPDATE:

_We are proud to announce that the 10th Annual PyLadies Auction  at @pycon will be held virtually!  A crowd favorite filled with fun, charity and competition !_

_Historically, we have used funds raised to support our worldwide community to thrive. Add your ticket to your registration today! https://us.pycon.org/2021/registration/information/ #PyLadies #PyCon2021_

**Comment by Marie-L** [comment]
@kittylon I've made the first post, let's work together to post the second one before the end of the week. Thanks for your help 🙏

**Comment by Marie-L** [comment]
2nd post

copy UPDATE:

A few more days left until the 10th Annual PyLadies Auction at @PyCon ! In 2019 we raised almost $50,000, join us to raise more this year for our worldwide community 🌍 ! Add the auction ticket to your registration today! https://us.pycon.org/2021/registration/information/

**Comment by Marie-L** [comment]
@kittylon I've just posted, when you have time can you please use the stats to make another similar post this week ? I will also aim to post again before saturday. Thanks for your help 🙏
