### ISSUE TITLE
Search for a few tech community group sites which have similar use cases

### ISSUE THREAD

**Issue by Marie-L** [pyladies/project-communications#9]
Research tech community groups which have similar aims and use cases to PyLadies and compile a list.

**Comment by Marie-L** [comment]
1. Women Who Code
2. Django Girls
3. Node Girls
4. Rails Girls

**Comment by Marie-L** [comment]
Research for the list above will be completed in #10

**Comment by BethanyG** [comment]
- Black Girls Code (https://www.blackgirlscode.com/blog)
- Women in Machine Learning and Data Science (http://wimlds.org/blog/)
- R-Ladies (https://blog.rladies.org/post/)
- DjangoProject (https://www.djangoproject.com/community/)
- Free Code Camp (https://www.freecodecamp.org/news/)

**Comment by Marie-L** [comment]
Thank you @BethanyG 🙏

**Comment by Marie-L** [comment]
This has been completed, so can now be closed.
