### ISSUE TITLE
Youtube Series "IWD PyLadies" (Reshama request)

### ISSUE THREAD

**Issue by cecivieira** [pyladies/project-communications#90]
Post in Instagram and Twitter 1 image about the Youtube Series "IWD PyLadies"  and schedule 30 twitter's post with each talk link.

**Checklist:**

- [x]  Ask Reshama, Tereza and Georgi for thumbnail;
- [x] Edit it for Instagram and Twitter;
- [x] Update the Comunnication-assets' repository;
- [ ] Announce the editable graphic with the repository link;
- [ ] Post in Instagram and Twitter a general post about the series;
~- [ ] Schedule at Zapier bot the 30 tweets, one of each talk [HOW TO DO THIS?], with this template message:~

#IWD2021pyladies
Today we feature [SPEAKER NAME] (SPEAKER-TWITTER)][ of [PYLADIES CHAPTER]
[TALK TITLE]
[VIDEO LINK]

**Comment by Marie-L** [comment]
@cecivieira Thanks for raising this issue. There are existing plans to promote all of the videos from our youtube page on a weekly basis. However, this will not be done via Zapier. I think it would be a good idea if we could create a plan with all of our video content in mind, what do you all think ?

**Comment by Marie-L** [comment]
Also, Tereza and Georgi have access to all the artwork (thumbnails) so you can ask them

**Comment by cecivieira** [comment]
@Marie-L where's the plans?
I'm thinking that we should start with Youtube Series "IWD PyLadies". How to post in twitter and instagram? 
How to work Zapier bot? PyLadies has a plataform for manage social media, like [Hootsuite](https://www.hootsuite.com).

**Comment by Marie-L** [comment]
Hey @cecivieira, sure we can start with IWD PyLadies. @kittylon has access to Buffer which is an alternative to Hootsuite. As we discussed before, we won't be using zapier for this campaign.

**Comment by Marie-L** [comment]
I'll get the ball rolling and post this:
 _International Women’s History Month is almost coming to a close but we will continue to showcase the awesome #PyLadies in our community ! So every few days, we will share a talk from our @YouTube series IWD PyLadies ! Don’t miss it 😜!_

**Comment by Marie-L** [comment]
@kittylon @AbigailDogbe @cecivieira @julianafalves Let's collect all the info we need in issue #91

**Comment by cecivieira** [comment]
@Marie-L in the caption you sad "(...)every few days, we will share a talk from our @youtube series Meet The PyLadies IWD 2021 Special !". Will you make all images for Instagram post?

I'm asking this because during the last meeting the attendees agreed that we would make 1 post with image in Instagram and the other ones will be only for twitter without image. However, I agree with individual posts with images if you could do this. What do you thinking @kittylon @julianafalves ?

Other points are to publish the caption in two languages and make the editable graphic, so in the next posts could you share on this issue the editable graphic and the original captions before publish? In this way we could contributing with this task

**Comment by Marie-L** [comment]
#91 will be closed as reshama has shared the info here : https://docs.google.com/spreadsheets/d/13wRM9x9NiNJhRpT9mP2uGR8FdqiNcmqZ6-Y1K0h_2e0/edit#gid=0

**Comment by Marie-L** [comment]
@cecivieira I'm only helping to get this started because at a minimum each week we need to make one post per day across social media platforms. You can use Georgi's graphics to create the instagram graphics.

Also, we have discussed in detail before that we will not translate post into only **two** languages. We are a **global** community, so we must try to be as fair as possible . Therefore, when we translate we will do so in our **seven** main languages. I hope you understand. Thanks !

**Comment by cecivieira** [comment]
@Marie-L sorry, I didn't entire plan with the translations... we thought using english + 1 any language. The structure of each post would be english and other language, so with this we bring all 7 languages over time.

About create 30 differents graphics, we could back to talk in the next meeting.

**Comment by Marie-L** [comment]
Point
1. we must have graphics for very post

**Comment by kittylon** [comment]
In addition, @cecivieira will add the details for the translations such as font, size, color palette so the people know what to use in the translations

**Comment by Marie-L** [comment]
First up: 

Today we feature @pyladiesbbk Thohirah Husaini's talk, Discover the Better Version of Yourself Everyday from our @youtube series Meet The PyLadies IWD 2021 Special ! #PyLadies https://youtu.be/rnc-dZtnzuM

**Comment by Marie-L** [comment]
hey everyone, who would like to decide who should be posted next ? Or does anyone have a time to write a script to generate a random list ?

**Comment by Marie-L** [comment]
Hey everyone, can you please share the details of who you'll post next in this issue? So that @AbigailDogbe can share it on LinkedIn too. Thanks !

**Comment by kittylon** [comment]
Hi Marie-Lou, sorry I had my notifications set up misconfig and I recently read this.

Is this still too late to answer?

**Comment by AbigailDogbe** [comment]
> Hi Marie-Lou, sorry I had my notifications set up misconfig and I recently read this.
> 
> Is this still too late to answer?

Hello @kittylon I don't think it is too late.

**Comment by AbigailDogbe** [comment]
@kittylon I would need a caption for the talk. Thank you!

**Comment by kittylon** [comment]
Sure, it's

`Today we feature Mariata's talk "Intro to Documentation using Sphinx and reStructuredtext" from our youtube series Meet The PyLadies IWD 2021 Special! #PyLadies`

let me know if you need anything else :)

**Comment by Marie-L** [comment]
@AbigailDogbe no worries, thanks for your help everyone 🙏

**Comment by kittylon** [comment]
Toda's post:
```
Today we feature @pyladiesbkk Chongko's talk "Creativity spice for Tech-savvy (น้ำจิ้มรสเด็ดของคนไอที)" from our youtube series Meet The PyLadies IWD 2021 Special! #PyLadies 

https://buff.ly/3i8ssPM
```

**Comment by kittylon** [comment]
today's post:
```
Today we feature  Ivy Fung's talk "I was supposed to be coding more, but ended up organizing more" from our youtube series Meet The PyLadies IWD 2021 Special! #PyLadies 

https://buff.ly/3c56MQW
```

**Comment by kittylon** [comment]
Not sure why, but apparently didn't click on comment:

@AbigailDogbe 
And tomorrow's one:
```
Today we feature @pyladiesbkk Chelsea Dole's talk "Understanding Python Memory Management" from our youtube series Meet The PyLadies IWD 2021 Special! #PyLadies 

https://buff.ly/3urhw2h

```
All the necessary images can be found here:
https://drive.google.com/drive/folders/1z_dP4ucLgXMNMLZPxsjcYjEWhbONc3qs

I will be offline this weekend, If you need anything else, you can contact us via slack

happy weekend!

**Comment by kittylon** [comment]
Today's post:
```
Today we feature #NYCPyLadies Reshama Shaikh's talk "The Hidden Depth of PyLadies" from our youtube series Meet The PyLadies IWD 2021 Special! #PyLadies 

https://www.youtube.com/watch?v=GgCB0-EjSnY
```

**Comment by kittylon** [comment]
Today's post
```
Today we feature Naomi Ceder and Carol Willing on "PyLadies Spotlight: PSF + Steering Council" from our youtube series Meet The PyLadies IWD 2021 Special, hosted by Lorena Mesa #PyLadies ⠀
⠀
https://buff.ly/3gf29ov
```

**Comment by kittylon** [comment]
I missed four days of comments 😔

should I also add them here? @AbigailDogbe ?

Apologies for not being consistent on commenting them here

**Comment by kittylon** [comment]
All post have been posted
