### ISSUE TITLE
IWD PyLadies Info

### ISSUE THREAD

**Issue by Marie-L** [pyladies/project-communications#91]
**Summary**

We need to collect the details of the participants involved in the YouTube series **Meet The PyLadies IWD Special**

**Acceptance Criteria**

- A table which lists details such as : 
   - Name
   - Talk title 
   - PyLadies Chapter
   - Location
   - Twitter handle
   - video link

**Do you want to work on this issue (Yes/No)?**

everyone involved can work on this 

cc / @pyladies/communications

**Comment by Marie-L** [comment]
Name| Talk title | PyLadies Chapter | Location  | Twitter handle|
| --| --| --| --| --|
||||||

**Comment by cecivieira** [comment]
Reshama shared in the original request on Slack:
https://docs.google.com/spreadsheets/d/13wRM9x9NiNJhRpT9mP2uGR8FdqiNcmqZ6-Y1K0h_2e0/edit#gid=0
