### ISSUE TITLE
Meeting notes : TEMPLATE

### ISSUE THREAD

**Issue by Marie-L** [pyladies/project-communications#94]
# Comms Weekly Hack Session

- Date: 
- Previous meeting minutes:
- Meeting Lead(s): 
- Notetaker: 
- Current meeting attendees: 

### Team Updates

- Calendar:
- Social media requests:
- Email requests :
- Blog updates :
- Project board updates :

### Review Actions Items from Last Meeting

Action Item| Owner | Relevant links | 
| --| --| --|
||||
||||
||||
||||

### New Business

- [ ] 
- [ ] 
- [ ] 
- [ ] 
---
### Old Business: Follow up items from prior meeting:
- [ ] 
- [ ] 
- [ ] 
- [ ]

### Action Items and Assignees for Next Meeting

Action Item| Owner | Relevant links | 
| --| --| --|
||||
||||
||||

cc / @pyladies/communications

**Comment by kittylon** [comment]
Template already in use
