### ISSUE TITLE
Pride Month 2021

### ISSUE THREAD

**Issue by Marie-L** [pyladies/project-communications#96]
Hi Ladies, 

Today is the first day of Pride month, what are your ideas on how we can celebrate this across our platforms ?

**Comment by kittylon** [comment]
Hi Marie-Lou, 

Tomorrow we have a session, I will reply the outcome to this thread ;)

I'm pretty sure it's a post, so probably will add it here once it's done

**Comment by Marie-L** [comment]
Thanks @kittylon, I really appreciate you 😊🙏 !

**Comment by Marie-L** [comment]
Also what do you think about adding pride flag banner on all of our platforms ?

**Comment by kittylon** [comment]
I'm up for it.

Regarding the meeting it did not take place due to a very unfortunate situation.

I will get back to you on saturday

**Comment by kittylon** [comment]
I got inspired and put this toguether in canva:

![Fight bigotry and hatred](https://user-images.githubusercontent.com/5789321/120716670-a83beb80-c4c6-11eb-85df-27cda866a1f2.png)
What do you think?

**Comment by Marie-L** [comment]
Love it, thank you @kittylon ! I'll ping you on slack to arrange a catch up 😊

**Comment by kittylon** [comment]
alright!

**Comment by julianafalves** [comment]
Hello all, I just saw this issue, I love your image Carolina <3. I also got inspired and made this image on canva:

<img width="810" alt="pride_month" src="https://user-images.githubusercontent.com/49698966/121384455-aa66d580-c91e-11eb-9804-94ec84658458.png">

**Comment by kittylon** [comment]
@lorenanicole can you please help us changing the twitter banner? 🙏🏻
![PRIDE 2021_banner](https://user-images.githubusercontent.com/5789321/121424047-31449e00-c971-11eb-854e-64470853f64e.png)
